python3 train.py \
  --train train.jsonl \
  --batch 16 \
  --epoch 2 \
  --embedding-dim 512 \
  --num-encoder-layers 4 \
  --num-decoder-layers 4 \
  --num-heads 8 \
  --feedforward-dim 512 \
  --batch-print 100 \
  --max-characters 500 \
  --output models.restore